import 'package:coinswapr/models/transaction.dart';

List<Transaction> transactions = [
  Transaction(
    title: 'Received',
    timestamp: DateTime.now(),
    fiatAmount: 11000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.inflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now(),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Received',
    timestamp: DateTime.now(),
    fiatAmount: 11000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.inflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now(),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Received',
    timestamp: DateTime.now(),
    fiatAmount: 11000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.inflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now(),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 1)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
  Transaction(
    title: 'Sent',
    timestamp: DateTime.now().add(const Duration(days: 2)),
    fiatAmount: 1000,
    cryptoAmount: 0.00023494,
    fiatSymbol: '\$',
    cryptoSymbol: 'btc',
    fiatCurrency: 'USD',
    cryptoCurrency: 'Bitcoin',
    type: TransactionType.outflow,
  ),
];
